services:
  hozbot:
    image: mhozza/hozbot
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hozbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - ./downloads:/app/downloads
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
